# Generated by Django 3.0.7 on 2020-07-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftlapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activity',
        ),
    ]
