# Generated by Django 3.0.7 on 2020-07-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftlapi', '0002_remove_user_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='completed',
        ),
        migrations.AlterField(
            model_name='user',
            name='id_num',
            field=models.IntegerField(),
        ),
    ]
